# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInvalid():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_invalid(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.NAME, "password").send_keys("fahmi")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-alert-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".oxd-alert-content-text").text == "Invalid credentials"
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("fahmi12")
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(2) .oxd-text").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(2) .oxd-text").text == "Required"
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(3) .oxd-text").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(3) .oxd-text").text == "Required"
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-login-slot-wrapper").click()
  
